### ISSUE TITLE
Карта google

### ISSUE THREAD

**Issue by mar294** [mar294/inter-polus.ru#1]
Заказчик потребовал подключить ему карту http://inter-polus.ru/3-nashi-proekty/ (внизу). Маркеры изменили по его требованию, но при уменьшении масштаба маркеры объединяются в дефолтный цвет.

**Comment by akochnov** [comment]
Леха, заменил иконку на желтую
http://puu.sh/gMeeK/5106fe9d71.jpg
Если хочешь кастомизировать - можешь взять исходники картинок для модификации отсюда:
http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m1.png
http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m2.png
и так далее меняй цифру в названии файла до 5

**Comment by mar294** [comment]
Это вся свобода выбора???????????????????

**Comment by mar294** [comment]
![grmarker](https://cloud.githubusercontent.com/assets/10448283/6830688/93fa2ffc-d32c-11e4-86e2-1d4aa752b86f.png)
Лёх, поправил цвет.

**Comment by akochnov** [comment]
Готово
http://puu.sh/gQ8OI/9128686a3b.jpg
