### ISSUE TITLE
Добавить картинки маркерам

### ISSUE THREAD

**Issue by mar294** [mar294/inter-polus.ru#4]
При наведении на маркер должен выпадать не только текст, а и картинка, которую можно добавить через админку. В админке есть штатная функция аттачивания картинок, не знаю, получится ли её использовать.

**Comment by akochnov** [comment]
Для карт на Главной странице и странице Контакты картинки во всплывающее окно можно добавлять в разделе "Маркеры" (Настройки->Модули->GoogleMaps->Маркеры->Редактировать). Поле Описание.
![image](https://cloud.githubusercontent.com/assets/9281874/7797041/68b8cd74-02ef-11e5-8c66-45b7bca87091.png)

![image](https://cloud.githubusercontent.com/assets/9281874/7797053/8fca9974-02ef-11e5-82af-06afcf526da7.png)

**Comment by akochnov** [comment]
Для карт в разделе "Наши Проекты" я добавил еще одно поле - "Описание" и реализовал вывод его во всплывающее окно маркера
Туда можно вставить любой хтмл, в том числе картинку, загруженную через админку:
![image](https://cloud.githubusercontent.com/assets/9281874/7797077/f7d518b4-02ef-11e5-80da-2c4de1201ebb.png)
![image](https://cloud.githubusercontent.com/assets/9281874/7797084/11133ef0-02f0-11e5-9d18-3aa67cee6798.png)

![image](https://cloud.githubusercontent.com/assets/9281874/7797094/4428cb8e-02f0-11e5-9a97-24ae17420797.png)
